# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.7 
    
# e.g. "Ben_millerius"    
species.name <- "Ben_millerius"
    
# e.g. "red"    
color <- "darkgreen"

    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
